apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx-conf: |
    user nginx;
    pid /var/run/nginx/nginx.pid;
    load_module /usr/lib/nginx/modules/ngx_stream_module.so;
    
    events {
        worker_connections 1024;
    }
    
    stream {
        upstream mysql-backend {
            server 10.10.50.111:3306;
            server 10.10.60.111:3306 backup;
        }
        server {
            listen 13306;
            proxy_pass mysql-backend;
        }
    }
