apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx-stream
  name: nginx-stream
spec:
  ports:
  - protocol: TCP
    port: 13306
    protocol: TCP
    targetPort: 13306
  selector:
    app: nginx-stream
  type: ClusterIP
status:
  loadBalancer: {}
